// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:DroneFlightLog.Mvc.Api.FlightSearchClient.#ctor(System.Net.Http.HttpClient,Microsoft.Extensions.Options.IOptions{DroneFlightLog.Mvc.Configuration.AppSettings},Microsoft.AspNetCore.Http.IHttpContextAccessor,DroneFlightLog.Mvc.Interfaces.ICacheWrapper)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:DroneFlightLog.Mvc.Controllers.MaintenanceRecordsSearchController.#ctor(DroneFlightLog.Mvc.Api.DroneClient,DroneFlightLog.Mvc.Api.MaintainersClient,DroneFlightLog.Mvc.Api.MaintenanceRecordClient,Microsoft.Extensions.Options.IOptions{DroneFlightLog.Mvc.Configuration.AppSettings})")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:DroneFlightLog.Mvc.Api.MaintenanceRecordClient.#ctor(System.Net.Http.HttpClient,Microsoft.Extensions.Options.IOptions{DroneFlightLog.Mvc.Configuration.AppSettings},Microsoft.AspNetCore.Http.IHttpContextAccessor,DroneFlightLog.Mvc.Interfaces.ICacheWrapper)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:DroneFlightLog.Mvc.Controllers.FlightsController.#ctor(DroneFlightLog.Mvc.Api.DroneClient,DroneFlightLog.Mvc.Api.LocationClient,DroneFlightLog.Mvc.Api.OperatorClient,DroneFlightLog.Mvc.Api.FlightClient,AutoMapper.IMapper)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:DroneFlightLog.Mvc.Controllers.MaintenanceRecordsController.#ctor(DroneFlightLog.Mvc.Api.DroneClient,DroneFlightLog.Mvc.Api.MaintainersClient,DroneFlightLog.Mvc.Api.MaintenanceRecordClient,AutoMapper.IMapper)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:DroneFlightLog.Mvc.Controllers.MaintenanceRecordsSearchController.#ctor(DroneFlightLog.Mvc.Api.DroneClient,DroneFlightLog.Mvc.Api.MaintenanceRecordClient,Microsoft.Extensions.Options.IOptions{DroneFlightLog.Mvc.Configuration.AppSettings})")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:DroneFlightLog.Mvc.Controllers.ModelsController.#ctor(DroneFlightLog.Mvc.Api.ManufacturerClient,DroneFlightLog.Mvc.Api.ModelClient,AutoMapper.IMapper)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:DroneFlightLog.Mvc.Api.DroneFlightLogClientBase._client")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:DroneFlightLog.Mvc.Api.DroneFlightLogClientBase._settings")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:DroneFlightLog.Mvc.Api.DroneFlightLogClientBase._cache")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:DroneFlightLog.Mvc.Api.AddressClient.#ctor(System.Net.Http.HttpClient,Microsoft.Extensions.Options.IOptions{DroneFlightLog.Mvc.Configuration.AppSettings},Microsoft.AspNetCore.Http.IHttpContextAccessor,DroneFlightLog.Mvc.Interfaces.ICacheWrapper)")]
