FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
MAINTAINER Dave Walker (david.walker5@icloud.com)
COPY droneflightlog.api-1.0.0.4 /opt/droneflightlog.api-1.0.0.4
WORKDIR /opt/droneflightlog.api-1.0.0.4/bin
ENTRYPOINT [ "./DroneFlightLog.Api" ]
