FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
MAINTAINER Dave Walker (david.walker5@icloud.com)
COPY droneflightlog.mvc-1.0.0.1 /opt/droneflightlog.mvc-1.0.0.1
WORKDIR /opt/droneflightlog.mvc-1.0.0.1/bin
ENTRYPOINT [ "./DroneFlightLog.Mvc" ]
