FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
MAINTAINER Dave Walker (david.walker5@icloud.com)
COPY droneflightlog.mvc-1.0.0.0 /opt/droneflightlog.mvc-1.0.0.0
WORKDIR /opt/droneflightlog.mvc-1.0.0.0
ENTRYPOINT [ "./DroneFlightLog.Mvc" ]
